### ISSUE TITLE
Consider removing lodash dependency

### ISSUE THREAD

**Issue by benjreinhart** [alex94puchades/superagent-jsonapify#4]
This is not a "lightweight client addon for superagent." You depend on lodash which pulls in ~12k LOC into my app. I'm not sure why the following wouldn't suffice:

```javascript
import request from 'superagent';

request.parse['application/vnd.api+json'] = JSON.parse;
request.serialize['application/vnd.api+json'] = JSON.stringify;

module.exports = request;
```

**Comment by alex94puchades** [comment]
If that works for you then for sure, don't use superagent-jsonapify. Where superagent-jsonapify excels is in transparent handling of [included fields](http://jsonapi.org/format/#fetching-includes) (I assume you have a brief understanding of the [jsonapi](http://jsonapi.org/format/) format).

Lodash brings ~12k LOC overhead. If that's the issue, we could reimplement part of lodash functionality, right? But bear in mind that superagent-jsonapify is such a tiny library (~70 LOC). If we went for that, 50% or more of the library could end up being utility routines already implemented by lodash, which is crazy!

Now, I assume you're talking client-side here, and so you're probably using something like browserify or webpack. And, since lodash is kind of ubiquitous, a dedupe + minify plugin is going to work for the majority of cases. No code duplication with negligible size overhead.

**Comment by benjreinhart** [comment]
I'm not using this. I was commenting on the dependency.

Also, doesn't lodash put each method into its own file? Can't you require only what you need? If so, you'd be able to remove a big portion of lodash from the resulting bundle.
